# Site settings
title:       Create.net Product Team Blog
email:       
author:      Create.net
description: "The Create.net product team blog."
baseurl:     "/blog"
url:         "http://developers.create.net/blog/"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: createdotnet
stackoverflow_id:
twitter_username: createdev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true


authors:
  aidan:
    name: Aidan Threadgold
    github: aidanthreadgold
    twitter: aidanthreadgold
    job: Developer
  andrada:
    name: Andrada Focsa
    github: 
    twitter: 
    job: Developer
  andy:
    name: Andy Hansen
    github: 
    twitter: 
    job: Designer
  benjamin:
    name: Benjamin Parry
    github: 
    twitter: 
    job: Front-end Designer
  ed:
    name: Ed Bailey
    github: 
    twitter: 
    job: Developer
  ed:
    name: Ian Booth
    github: 
    twitter: 
    job: Product Manager
  joel:
    name: Joel Day
    github: 
    twitter: 
    job: Senior Developer
  matt:
    name: Matt Greenfield
    github: 
    twitter: 
    job: Designer
  simon:
    name: Simon Kimber
    github: 
    twitter: 
    job: CTO/Devops